### ISSUE TITLE
building hawaii-system-preferences

### ISSUE THREAD

**Issue by staalmannen** [hawaii-desktop/hawaii-pkgbuilds#11]
The following cmake error occurs:

CMake Error at CMakeLists.txt:36 (add_custom_target):
  add_custom_target cannot create target "uninstall" because another target
  with the same name already exists.  The existing target is a custom target
  created in source directory
  "/home/jens/Devel/Arch/Hawaii/hawaii-pkgbuilds/hawaii-system-preferences-git/src/system-preferences".
  See documentation for policy CMP0002 for more details.

**Comment by plfiorini** [comment]
See hawaii-desktop/hawaii-system-preferences#30

**Comment by plfiorini** [comment]
Closing, now it builds.
Please reopen if you still have build issues.
