### ISSUE TITLE
Packages still not building due to incorrect version check

### ISSUE THREAD

**Issue by flamusdiu** [hawaii-desktop/hawaii-pkgbuilds#12]
I am getting: `qtconfiguration-git-v*-1-x86_64.pkg.tar.xz doesn't exist!` when trying to build the package set. However, the build script creates `qtconfiguration-git-20140413.804739d-1-x86_64.pkg.tar.xz` and what the script is looking for doesn't exists.

**Comment by plfiorini** [comment]
whops i haven't touched that yet because i haven't done any work in it lately

**Comment by plfiorini** [comment]
Script updated, testing in the morning

**Comment by flamusdiu** [comment]
```
==> Installing missing dependencies...
error: target not found: greenisland-git
==> ERROR: 'pacman' failed to install missing dependencies.

==> ERROR: Build failed, check /home/jesse/chroot/jesse/build
hawaii-shell-git*.pkg.tar.xz doesn't exist!
```
This is better! Getting there. I noticed you are not building the greenisland-git package.

**Comment by plfiorini** [comment]
Geez I'm not giving a spin to this script in a long time, usually i build each package one by one or use yaourt on the laptop.

**Comment by plfiorini** [comment]
Fixed the order, let's if that fixed

**Comment by flamusdiu** [comment]
@plfiorini well, I have `aura` installed that I use for AUR packages. What would be the preferred method of installing/building?

**Comment by flamusdiu** [comment]
@plfiorini I think you should either support the script or support installing through AUR. I think using both methods might be come a bit of taunting task to keep both up-to-date and working considering how much development is going on with the desktop environment.

**Comment by flamusdiu** [comment]
```
==> Making package: greenisland-git 20150222.1e69fe2-1 (Tue Mar 31 18:15:27 EDT 2015)
==> Retrieving sources...
  -> Cloning greenisland git repo...
Cloning into bare repository '/home/jesse/git_projects/hawaii-pkgbuilds/greenisland-git/greenisland'...
remote: Counting objects: 6399, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 6399 (delta 0), reused 0 (delta 0), pack-reused 6392
Receiving objects: 100% (6399/6399), 1.44 MiB | 0 bytes/s, done.
Resolving deltas: 100% (4480/4480), done.
Checking connectivity... done.
==> Validating source files with md5sums...
    greenisland ... Skipped
==> Making package: greenisland-git 20150222.1e69fe2-1 (Tue Mar 31 18:15:29 EDT 2015)
==> Checking runtime dependencies...
==> Installing missing dependencies...
error: target not found: hawaii-qt5-wayland-git
==> ERROR: 'pacman' failed to install missing dependencies.

==> ERROR: Build failed, check /home/jesse/chroot/jesse/build
greenisland-git*.pkg.tar.xz doesn't exist!
```

**Comment by flamusdiu** [comment]
Just to note: the `hawaii-meta-git- package on AUR builds find with `aura` (using `sudo aura -Aakxu hawaii-meta-git`). =)

**Comment by plfiorini** [comment]
The scripts here were used by me to build the binary archives, the preferred method would be to build from AUR with whatever tool one prefers.

AUR is always kept updated now thanks to the mksource-hawaii script that will also upload the pkgbuilds for me (so less chances that I forget to do it because now it's just a matter of running a script).

**Comment by flamusdiu** [comment]
Well, if the preferred way to build them is from AUR, then I would just move the scripts to your abandoned branch for now and make a note on the Readme. Then can close this issue. =)
