### ISSUE TITLE
hawaii-archiver-git does build

### ISSUE THREAD

**Issue by flamusdiu** [hawaii-desktop/hawaii-pkgbuilds#14]
Building from https://aur.archlinux.org/packages/hawaii-archiver-git/ doesn't work. It's missing `hawaii-vibe-git` package in AUR.

**Comment by plfiorini** [comment]
I haven't done work on this for a long time, moving the package out of sight in the abandoned branch so users are not misleaded.

Will come back once the shell is mature enough for day to day use and so my hands are free to code something else :)

**Comment by flamusdiu** [comment]
Rgr. No worries. I was just pointing out the issue. =)
